import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Dashboard.module.css'
import useAuth from '../hooks/useAuth'

export default function Dashboard() {

  const { user } = useAuth();

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <div>
          <Link href="/sobre">
            <a>
            <span>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
            </a>
        </Link>
        <nav>
            <ul>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
                <li>
                    <Link href="/sobre">
                        <a>Notes</a>
                    </Link>
                </li>
            </ul>
        </nav>
        <span>
            <button>Search</button>
            <button>Ac</button>
        </span>
        </div>
      </header>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {user?.displayName}
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
